"use client";
import { useState } from "react";
import { api, ApiDebtPlan } from "@/lib/api-client";
import { formatCurrency, type Account } from "@/lib/data";
import { Button } from "@/components/ui/button";
export function DebtPlanDialog({ accounts, onClose }: { accounts: Account[]; onClose: () => void }) {
  const [strategy, setStrategy] = useState<"avalanche" | "snowball">("avalanche"); const [extra, setExtra] = useState("0"); const [plan, setPlan] = useState<ApiDebtPlan | null>(null); const [error, setError] = useState("");
  async function calculate() { try { setError(""); setPlan(await api.simulations.debtOptimization({ account_ids: accounts.map((a) => a.id), extra_monthly_payment: extra, strategy })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to calculate payoff plan."); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-lg border border-border bg-card p-4 shadow-xl"><h2 className="text-sm font-semibold">Plan debt payoff</h2><p className="mt-1 text-xs text-muted-foreground">Uses current balances and saved debt terms. This comparison is not persisted.</p><div className="mt-4 grid grid-cols-2 gap-2"><select className="h-8 rounded-md border border-border bg-background px-2 text-xs" value={strategy} onChange={(e) => setStrategy(e.target.value as typeof strategy)}><option value="avalanche">Avalanche · highest APR</option><option value="snowball">Snowball · smallest balance</option></select><input className="h-8 rounded-md border border-border bg-background px-2 text-xs" type="number" min="0" value={extra} onChange={(e) => setExtra(e.target.value)} placeholder="Extra monthly payment" /></div>{plan && <div className="mt-4 rounded-md border border-border bg-muted/30 p-3 text-xs"><p className="font-medium">{plan.paid_off ? `Debt-free in ${plan.months_to_debt_free} months` : "Not paid off within model horizon"}</p><p className="mt-1 text-muted-foreground">Estimated interest: {formatCurrency(Number(plan.total_interest_paid))}</p><p className="mt-1 text-muted-foreground">Order: {plan.payoff_order.join(" → ") || "None"}</p>{plan.warning && <p className="mt-2 text-warning">{plan.warning}</p>}</div>}{error && <p className="mt-3 text-xs text-destructive">{error}</p>}<div className="mt-4 flex justify-end gap-2"><Button variant="outline" size="sm" onClick={onClose}>Close</Button><Button size="sm" onClick={() => void calculate()}>Calculate</Button></div></div></div>;
}
