"""plaid_link_support

Revision ID: 26080919f0f4
Revises: c9eb03887309
Create Date: 2026-07-18 21:39:48.285862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26080919f0f4'
down_revision: Union[str, None] = 'c9eb03887309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('plaid_access_token_encrypted', sa.Text(), nullable=True))
    op.add_column('institutions', sa.Column('plaid_sync_cursor', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_institutions_external_item_id', 'institutions', ['external_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_institutions_external_item_id', 'institutions', type_='unique')
    op.drop_column('institutions', 'plaid_sync_cursor')
    op.drop_column('institutions', 'plaid_access_token_encrypted')
    # ### end Alembic commands ###
