"""monthly_sustainable_withdrawal

Revision ID: 6460b9d29ec3
Revises: 26080919f0f4
Create Date: 2026-07-19 03:48:15.692634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6460b9d29ec3'
down_revision: Union[str, None] = '26080919f0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('monthly_sustainable_withdrawal', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'monthly_sustainable_withdrawal')
    # ### end Alembic commands ###
