"""scenario_cascade_and_retirement_trajectory

Revision ID: 684bcd78a7dd
Revises: 6460b9d29ec3
Create Date: 2026-07-21 01:03:45.091457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '684bcd78a7dd'
down_revision: Union[str, None] = '6460b9d29ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('retirement_trajectory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('simulation_runs_scenario_id_fkey'), 'simulation_runs', type_='foreignkey')
    op.create_foreign_key(None, 'simulation_runs', 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation_runs', type_='foreignkey')
    op.create_foreign_key(op.f('simulation_runs_scenario_id_fkey'), 'simulation_runs', 'scenarios', ['scenario_id'], ['id'])
    op.drop_column('simulation_runs', 'retirement_trajectory')
    # ### end Alembic commands ###
