"""desired_monthly_income_today

Revision ID: 8d1776d4438a
Revises: 684bcd78a7dd
Create Date: 2026-07-22 05:01:26.255011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d1776d4438a'
down_revision: Union[str, None] = '684bcd78a7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('desired_monthly_income_today', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'desired_monthly_income_today')
    # ### end Alembic commands ###
